name: moneta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.4+4
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.13
  flutter_local_notifications: ^9.1.4
  intl: ^0.17.0
  provider: ^6.0.3
  logger: ^1.1.0
  pdf: ^3.3.0
  syncfusion_flutter_charts: ^20.4.45
  printing: ^5.6.1
  syncfusion_flutter_pdf: ^20.4.54
  charts_flutter: ^0.12.0
  path_provider: ^2.0.11

    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  

flutter:

  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/moneta-logo-2.png
    - assets/images/on-boarding-screen-first.png
    - assets/images/on-boarding-screen-second.png
    - assets/images/on-boarding-screen-third.png
    - assets/images/on-boarding-screen-fourth.png
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
